apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example 
  namespace: my-namespace
roleRef: 
  apiGroup: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io/v1
  kind: User
  name: myuser