# Here we create a namespace which include the lables that include in the book.
# It's possible to create namespace at first and lable it after like:
  # kubectl label namespace my-namespace \
  # pod-security.kubernetes.io/warn=restricted \
  # pod-security.kubernetes.io/audit=restricted


apiVersion: v1
kind: Namespace
metadata:
  name: podsec
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.25
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: v1.25
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: v1.25

 
