apiVersion: v1
kind: Service
metadata:
  labels: 
    app: frontend
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP